### ISSUE TITLE
Does it still works ?

### ISSUE THREAD

**Issue by Waheymans** [naxvog/wpr-redis#2]
Does it still works?

This because i still got the message "Redis server went away"

Thanks in advanced

**Comment by naxvog** [comment]
The error message does hint to your connection settings being wrong. Will test the functionality against the newest WP-Rocket today.

**Comment by naxvog** [comment]
Sorry for the delay. Just confirmed that the plugin still works using WP Rocket v.3.5.5.1
Will add a notice in the readme to reflect the latest tested WP Rocket version.
